config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,
             path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'},
             controllers: { registrations: 'registrations' }

  devise_scope :customer do
    get 'login', to: 'devise/sessions#new'
    get 'register', to: 'devise/registrations#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end

  root 'shops#show'

  resource :profile, only: :show
  resource :shop, only: :show do
    get 'cart'
  end

  namespace :admin do
    get '/', to: 'products#index'
    resources :products, except: :show
    devise_for :admins, path: 'auth',
               path_names: {sign_in: 'login', sign_out: 'logout'}, as: :auth, singular: :admin,
               controllers: {sessions: 'devise/sessions'}, class_name: 'Admin'
  end

  namespace :api do
    resources :orders, only: :index
    resources :products, only: :index
    resource :me, only: :show, controller: :customers
    resources :charges, only: :create
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are: , :trackable, :validatable
  # :confirmable, :lockable, :timeoutable and :omniauthable :registerable,  :recoverable,

  devise :database_authenticatable, :rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :recoverable,
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name
  validates_length_of :password, minimum: 7

  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :items, class_name: OrderItem

  validates_presence_of :customer

  before_validation :generate_order_no


  def date
    created_at.strftime('%-d/%-m/%Y')
  end

  def recalculate_total!
    update_attribute(:total, items.sum(&:total_price))
  end

  def items_count
    items.size
  end

  private
    def generate_order_no
      while order_no.nil?
        random_token = SecureRandom.uuid.first(6)
        self.order_no = random_token unless self.class.exists?(order_no: random_token)
      end
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates_presence_of :order, :product

  before_validation do
    self.unit_price = product.price if self.unit_price == 0.0 && product.present?
    self.total_price = self.unit_price * self.qty
  end

  after_commit :update_total_of_order

  private
    def update_total_of_order
      self.order.recalculate_total!
    end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates_presence_of :description, :price
  validates :status, presence: true, inclusion: {in: [0, 1]}

  after_initialize do
    self.status ||= 1
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.order(created_at: :desc)
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_url, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to admin_products_url, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_products_url, notice: 'Product was successfully destroyed.'
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, :description, :status)
    end
end

app/controllers/api/charges_controller.rb
class Api::ChargesController < BaseController

  def create
    p transaction_url
    products = Product.find(params[:items])

    response = charge_card(products.sum(&:price))

    if response['success']
      order = Order.create!(customer: current_customer)
      products.each {|p| order.items.create(product: p)}
    end

    render json: response
  end

  private
    def charge_card(amount)
      data = {card_no: params[:card_no], amount: amount}
      r = Net::HTTP.post_form transaction_url, data

      JSON.parse(r.body)
    end

    def transaction_url
      c = Rails.application.config.payment_gateway
      uri = URI('%s/transactions' % c[:url])
      uri.user = c[:username]
      uri.password = c[:password]
      uri
    end

end

app/controllers/api/customers_controller.rb
class Api::CustomersController < BaseController
  def show
    render json: current_customer
  end
end

app/controllers/api/orders_controller.rb
class Api::OrdersController < BaseController
  def index
    render json: orders_hash
  end

  private
    def orders_hash
      current_customer.orders.includes(:items).map{|o| {order_no: o.order_no, total: (sprintf '%.2f', o.total), date: o.created_at, items_count: o.items_count}}
    end

end

app/controllers/api/products_controller.rb
class Api::ProductsController < BaseController
  skip_before_action :authenticate_customer!, only: :index

  def index
    render json: products_hash
  end

  private
    def products_hash
      # Product.all.map{|o| {name: o.order_no, price: (sprintf '%.2f', o.price), description: o.description, status: o.status}}
      Product.all
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :authenticate_customer!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < BaseController

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
    def sign_up_params
      params.require(:customer).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/controllers/shops_controller.rb
class ShopsController < BaseController
  skip_before_action :authenticate_customer!, only: :show

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div class="alert alert-warning alert-block">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h5>There are some errors</h5>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def cart_items
    JSON.parse (cookies[:_cart] || '[]')
  end
end

app/views/admin/products/_form.html.slim
= form_for([:admin, @product], html: { class: 'form-horizontal', role: 'form' }) do |f|
  - if @product.errors.any?
    .alert.alert-danger.alert-dismissable role='alert'
      button.close type='button' data-dismiss='alert'
        span aria-hidden='true'
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@product.errors.count,'error')} prohibited this product from being saved:"
      ul
        - @product.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :price, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :price, class: 'form-control'
  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :description, class: 'form-control'
  /.form-group
    = f.label :status, class: 'col-sm-2 control-label'
    .col-sm-10
      /= f.select :status, options_for_select({'Enabled': 1, 'Disabled': 0}) class: 'form-control'
      = f.radio_button :status, 1
  .form-group
    = f.label :status, 'Enabled', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.radio_button :status, 1, class: 'form-control'
  .form-group
    = f.label :status, 'Disabled', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.radio_button :status, 0, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/admin/products/edit.html.slim
.page-header
  = link_to admin_products_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back
  h1 Editing  product

= render 'form'

app/views/admin/products/index.html.slim
.page-header
  = link_to new_admin_product_path, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-plus
    |  New Product
  h1
    | Listing products

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th Name
        th Price
        th Description
        th Status
        th Created
        th
        th
    tbody
      - @products.each do | product |
        tr
          td= product.name
          td= product.price
          td= product.description
          td
            - if product.status == 1
              span.label.label-info Enabled
            - else
              span.label.label-warning Disabled
          td= product.created_at.to_formatted_s(:short)
          td= link_to 'Edit', edit_admin_product_path(product)
          td= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/products/new.html.slim
.page-header
  = link_to admin_products_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1 New product

= render 'form'

app/views/layouts/application.html.slim
doctype html
html
  head
    title CrossBooks | Ultimate Book Shop
    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all'


  body
    nav.navbar.navbar-default
      .container
        .navbar-header
          a.navbar-brand href='/' CrossBooks
        ul.nav.navbar-nav
          li= link_to 'Shop', shop_path
          li= link_to cart_shop_path do
            ' View Cart
            span.badge.nav-cart-items<= cart_items.size
        ul.nav.navbar-nav.navbar-right
          - if customer_signed_in?
            .navbar-text= "Welcome #{current_customer.first_name}"
            li= link_to 'My Orders', profile_path
            li= link_to 'Logout', logout_path, method: :delete
          - elsif admin_signed_in?
            .navbar-text= "Welcome Admin (#{current_admin.email})"
            li= link_to 'Products', admin_products_path
            li= link_to 'Logout', destroy_admin_session_path, method: :delete
          - else
            li= link_to 'Login', login_path
            li= link_to 'Register', register_path

    main.container
      - if notice
        .alert.alert-dismissible.alert-success
          button.close type="button" data-dismiss="alert" ×
          = notice
      - if alert
        .alert.alert-dismissible.alert-warning
          button.close type="button" data-dismiss="alert" ×
          = alert

      = yield

    = javascript_include_tag 'application'

app/views/pages/home.html.erb
<h1>{{message}}</h1>

app/views/profiles/show.html.erb
<div id="orders">
  <table class="table table-striped">
    <thead>
    <tr>
      <th v-for="column in columns"
          @click="sortBy(column)"
          :class="{active: sortKey == column}">
        {{column | capitalize}}
        <span class="arrow" :class="sort_class(column)"></span>
      </th>
    </tr>
    </thead>
    <tbody>
    <tr v-for="order in orders | orderBy sortKey sort ">
      <td><strong>#{{order.order_no}}</strong></td>
      <td>US ${{order.total}}</td>
      <td>{{order.items_count}}</td>
      <td>{{order.date.toDateString()}}</td>
    </tr>
    </tbody>
  </table>
</div>

app/views/shops/cart.html.erb
<div id="cart">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">Shopping Cart</h3>
    </div>
    <div class="panel-body" v-show="cart_items.length">

      <div class="alert alert-dismissible alert-danger" v-show="!!error_message">
        <button class="close" type="button" data-dismiss="alert">×</button>
        <strong>{{error_message}}</strong>
      </div>

      <table class="table table-striped">
        <tbody>
          <tr v-for="item in items">
            <td><strong>#{{$index+1}}</strong></td>
            <td>{{item.name}}</td>
            <td>US ${{item.price}} x1</td>
            <td>US ${{item.price}}</td>
            <td>
              <span class="remove" @click="remove_from_cart(item.id)">x</span>
            </td>
          </tr>

          <tr>
            <td></td><td></td>
            <td><strong>Grand Total</strong></td>
            <td><strong>US ${{total_price}}</strong></td>
            <td></td>
          </tr>

        </tbody>
      </table>
      <div class="row">
        <a href="/shop" class="btn btn-info">Continue shopping!</a>
        <div class="pull-right">
          <button class="btn btn-success checkout" @click="show_payment = true">Checkout</button>
        </div>
      </div>

      <div class="row" v-show="show_payment">
        <form class="col-md-8 col-md-offset-2" @submit="create_order">
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= label_tag :first_name %>
                <%= text_field_tag :first_name, nil, class: 'form-control', 'v-model': 'user.first_name' %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= label_tag :last_name %>
                <%= text_field_tag :last_name, nil, class: 'form-control', 'v-model': 'user.last_name' %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= label_tag :card_no %>
            <%= text_field_tag :card_no, nil, autofocus: true, class: 'form-control', 'v-model': 'user.card', required: true %>
          </div>

          <input type="submit" class="form-control btn btn-success" value="Confirm Order">
        </form>
      </div>
    </div>
    <div class="panel-body" v-show="!cart_items.length && !shopping_done">
      Cart Empty!  <a href="/shop" class="btn btn-success btn-lg">Go ahead and do some shopping!</a>
    </div>

    <div class="panel-body" v-show="!cart_items.length && shopping_done">
      Congrats!  <a href="/profile" class="btn btn-success btn-lg">Checkout your orders!</a>
    </div>
  </div>
</div>

app/views/shops/show.html.erb
<div id="products">
  <div class="row book-search">
    <div class="col-md-11">
      <input type="search" class="form-control form-group-lg" v-model="search" placeholder="Hit the keyboard and Filter the books">
    </div>

    <div class="col-md-1" v-show="cart.length">
      <a class="btn btn-success btn-group-lg" href="<%= cart_shop_path %>">View Cart <span class="view-count badge">{{cart.length}}</span></a>
    </div>
  </div>


  <table class="table table-striped">
    <thead>
    <tr>
      <th v-for="column in columns"
          @click="sortBy(column)"
          :class="{active: sortKey == column}">
        {{column | capitalize}}
        <span class="arrow" :class="sort_class(column)"></span>
      </th>
    </tr>
    </thead>
    <tbody>
    <tr v-for="product in products | filterBy search in 'name' | orderBy sortKey sort ">
      <td><strong>{{product.name}}</strong></td>
      <td>{{product.description}}</td>
      <td>US ${{product.price}}</td>
      <td>
        <button v-show="product.status && !in_cart(product.id)" @click="add_to_cart(product.id)" class="btn btn-info btn-xs">Buy Now</button>
        <button v-show="in_cart(product.id)" @click="remove_from_cart(product.id)" class="btn btn-danger btn-xs">Remove</button>
        <span class="label label-warning" v-show="!product.status">Unavilable!</span>
      </td>
    </tr>
    </tbody>
  </table>
</div>